services:
  - type: web
    name: telegram-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node backend/server.js
    envVars:
      - key: NODE_VERSION
        value: 22.12.0
      - key: MAGICAPI_KEY
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: ADMIN_SECRET
        generateValue: true
      - key: PUBLIC_URL
        sync: false
